# Generated by Django 5.1.6 on 2025-04-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_iyzico_payment_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="stripe_transaction_id",
            new_name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_payment_intent_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_payment_method_id",
        ),
    ]
