# Generated by Django 5.1.6 on 2025-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("traveler", "Traveler"),
                    ("sender", "Sender"),
                    ("admin", "Admin"),
                ],
                default="traveler",
                max_length=10,
            ),
        ),
    ]
