# Generated by Django 5.1.6 on 2025-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="booking_id",
            field=models.UUIDField(default="00000000-0000-0000-0000-000000000000"),
            preserve_default=False,
        ),
    ]
