# Generated by Django 5.1.6 on 2025-03-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_rating_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
