# Generated by Django 5.1.6 on 2025-04-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_stripe_account_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="stripe_account_id",
        ),
    ]
