# Generated by Django 5.1.6 on 2025-03-06 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Base price per kg for package delivery",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "tier1_max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Maximum weight for tier 1 pricing",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "tier1_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Price per kg for tier 1 weight",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "tier2_max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Maximum weight for tier 2 pricing",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "tier2_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Price per kg for tier 2 weight",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "tier3_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Price per kg for tier 3 weight (above tier 2 max weight)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Platform fee percentage on each transaction",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
